In [1]:
import duckdb
import pandas as pd
# No need to import duckdb_engine
#  jupysql will auto-detect the driver needed based on the connection string!

# Import jupysql Jupyter extension to create SQL cells
%load_ext sql

Deploy Panel apps for free on Ploomber Cloud! Learn more: https://ploomber.io/s/signup

In [2]:
%config SqlMagic.autopandas = True
%config SqlMagic.feedback = False
%config SqlMagic.displaycon = False

In [3]:
%sql duckdb:///artifacts/us_data.db

In [4]:
%sql us_data_df << SELECT * FROM read_csv('artifacts/us_data.csv') LIMIT 10;
us_data_df

,STATION,DATE,LATITUDE,LONGITUDE,ELEVATION,NAME,DP01,DP01_ATTRIBUTES,DP10,DP10_ATTRIBUTES,...,MX05,MX05_ATTRIBUTES,MX06,MX06_ATTRIBUTES,MX07,MX07_ATTRIBUTES,MX08,MX08_ATTRIBUTES,MX09,MX09_ATTRIBUTES
0,US1MDFR0038,2019-08-01,39.419264,-77.430926,100.0,"FREDERICK 1.0 SW, MD US",9.0,",N",5.0,",N",...,None,None,None,None,None,None,None,None,None,None
1,US1MDFR0038,2019-09-01,39.419264,-77.430926,100.0,"FREDERICK 1.0 SW, MD US",5.0,",N",3.0,",N",...,None,None,None,None,None,None,None,None,None,None
2,US1MDFR0038,2019-10-01,39.419264,-77.430926,100.0,"FREDERICK 1.0 SW, MD US",12.0,",N",10.0,",N",...,None,None,None,None,None,None,None,None,None,None
3,US1MDFR0038,2019-12-01,39.419264,-77.430926,100.0,"FREDERICK 1.0 SW, MD US",14.0,"1,N",8.0,"1,N",...,None,None,None,None,None,None,None,None,None,None
4,US1MDFR0038,2020-01-01,39.419264,-77.430926,100.0,"FREDERICK 1.0 SW, MD US",11.0,",N",6.0,",N",...,None,None,None,None,None,None,None,None,None,None
5,US1MDFR0038,2020-02-01,39.419264,-77.430926,100.0,"FREDERICK 1.0 SW, MD US",15.0,",N",7.0,",N",...,None,None,None,None,None,None,None,None,None,None
6,US1MDFR0038,2020-03-01,39.419264,-77.430926,100.0,"FREDERICK 1.0 SW, MD US",20.0,",N",8.0,",N",...,None,None,None,None,None,None,None,None,None,None
7,US1MDFR0038,2020-04-01,39.419264,-77.430926,100.0,"FREDERICK 1.0 SW, MD US",19.0,",N",9.0,",N",...,None,None,None,None,None,None,None,None,None,None
8,US1MDFR0038,2020-05-01,39.419264,-77.430926,100.0,"FREDERICK 1.0 SW, MD US",14.0,",N",9.0,",N",...,None,None,None,None,None,None,None,None,None,None
9,US1MDFR0038,2020-06-01,39.419264,-77.430926,100.0,"FREDERICK 1.0 SW, MD US",10.0,"1,N",7.0,"1,N",...,None,None,None,None,None,None,None,None,None,None

In [9]:
us_data_df.dtypes.to_dict()

{'STATION': dtype('O'),
 'DATE': dtype('<M8[us]'),
 'LATITUDE': dtype('float64'),
 'LONGITUDE': dtype('float64'),
 'ELEVATION': dtype('float64'),
 'NAME': dtype('O'),
 'DP01': dtype('float64'),
 'DP01_ATTRIBUTES': dtype('O'),
 'DP10': dtype('float64'),
 'DP10_ATTRIBUTES': dtype('O'),
 'DP1X': dtype('float64'),
 'DP1X_ATTRIBUTES': dtype('O'),
 'DYXP': dtype('float64'),
 'DYXP_ATTRIBUTES': dtype('O'),
 'EMXP': dtype('float64'),
 'EMXP_ATTRIBUTES': dtype('O'),
 'PRCP': dtype('float64'),
 'PRCP_ATTRIBUTES': dtype('O'),
 'DSNW': dtype('float64'),
 'DSNW_ATTRIBUTES': dtype('O'),
 'DYSN': dtype('float64'),
 'DYSN_ATTRIBUTES': dtype('O'),
 'EMSN': dtype('float64'),
 'EMSN_ATTRIBUTES': dtype('O'),
 'SNOW': dtype('float64'),
 'SNOW_ATTRIBUTES': dtype('O'),
 'ADPT': dtype('float64'),
 'ADPT_ATTRIBUTES': dtype('O'),
 'ASLP': dtype('float64'),
 'ASLP_ATTRIBUTES': dtype('O'),
 'ASTP': dtype('float64'),
 'ASTP_ATTRIBUTES': dtype('O'),
 'AWBT': dtype('float64'),
 'AWBT_ATTRIBUTES': dtype('O'),
 'AWND': dtype('float64'),
 'AWND_ATTRIBUTES': dtype('O'),
 'CDSD': dtype('float64'),
 'CDSD_ATTRIBUTES': dtype('O'),
 'CLDD': dtype('float64'),
 'CLDD_ATTRIBUTES': dtype('O'),
 'DSND': dtype('float64'),
 'DSND_ATTRIBUTES': dtype('O'),
 'DT00': dtype('float64'),
 'DT00_ATTRIBUTES': dtype('O'),
 'DT32': dtype('float64'),
 'DT32_ATTRIBUTES': dtype('O'),
 'DX32': dtype('float64'),
 'DX32_ATTRIBUTES': dtype('O'),
 'DX70': dtype('float64'),
 'DX70_ATTRIBUTES': dtype('O'),
 'DX90': dtype('float64'),
 'DX90_ATTRIBUTES': dtype('O'),
 'DYFG': dtype('float64'),
 'DYFG_ATTRIBUTES': dtype('O'),
 'DYHF': dtype('float64'),
 'DYHF_ATTRIBUTES': dtype('O'),
 'DYNT': dtype('float64'),
 'DYNT_ATTRIBUTES': dtype('O'),
 'DYSD': dtype('float64'),
 'DYSD_ATTRIBUTES': dtype('O'),
 'DYTS': dtype('float64'),
 'DYTS_ATTRIBUTES': dtype('O'),
 'DYXT': dtype('float64'),
 'DYXT_ATTRIBUTES': dtype('O'),
 'EMNT': dtype('float64'),
 'EMNT_ATTRIBUTES': dtype('O'),
 'EMSD': dtype('float64'),
 'EMSD_ATTRIBUTES': dtype('O'),
 'EMXT': dtype('float64'),
 'EMXT_ATTRIBUTES': dtype('O'),
 'EVAP': dtype('float64'),
 'EVAP_ATTRIBUTES': dtype('O'),
 'HDSD': dtype('float64'),
 'HDSD_ATTRIBUTES': dtype('O'),
 'HN01': dtype('float64'),
 'HN01_ATTRIBUTES': dtype('O'),
 'HTDD': dtype('float64'),
 'HTDD_ATTRIBUTES': dtype('O'),
 'HX01': dtype('float64'),
 'HX01_ATTRIBUTES': dtype('O'),
 'LN01': dtype('float64'),
 'LN01_ATTRIBUTES': dtype('O'),
 'LX01': dtype('float64'),
 'LX01_ATTRIBUTES': dtype('O'),
 'MN01': dtype('float64'),
 'MN01_ATTRIBUTES': dtype('O'),
 'MNPN': dtype('O'),
 'MNPN_ATTRIBUTES': dtype('O'),
 'MX01': dtype('float64'),
 'MX01_ATTRIBUTES': dtype('O'),
 'MXPN': dtype('O'),
 'MXPN_ATTRIBUTES': dtype('O'),
 'PSUN': dtype('O'),
 'PSUN_ATTRIBUTES': dtype('O'),
 'RHAV': dtype('float64'),
 'RHAV_ATTRIBUTES': dtype('O'),
 'RHMN': dtype('float64'),
 'RHMN_ATTRIBUTES': dtype('O'),
 'RHMX': dtype('float64'),
 'RHMX_ATTRIBUTES': dtype('O'),
 'TAVG': dtype('float64'),
 'TAVG_ATTRIBUTES': dtype('O'),
 'TMAX': dtype('float64'),
 'TMAX_ATTRIBUTES': dtype('O'),
 'TMIN': dtype('float64'),
 'TMIN_ATTRIBUTES': dtype('O'),
 'TSUN': dtype('O'),
 'TSUN_ATTRIBUTES': dtype('O'),
 'WDF1': dtype('O'),
 'WDF1_ATTRIBUTES': dtype('O'),
 'WDF2': dtype('float64'),
 'WDF2_ATTRIBUTES': dtype('O'),
 'WDF5': dtype('float64'),
 'WDF5_ATTRIBUTES': dtype('O'),
 'WDFG': dtype('float64'),
 'WDFG_ATTRIBUTES': dtype('O'),
 'WDFM': dtype('O'),
 'WDFM_ATTRIBUTES': dtype('O'),
 'WDMV': dtype('float64'),
 'WDMV_ATTRIBUTES': dtype('O'),
 'WSF1': dtype('O'),
 'WSF1_ATTRIBUTES': dtype('O'),
 'WSF2': dtype('float64'),
 'WSF2_ATTRIBUTES': dtype('O'),
 'WSF5': dtype('float64'),
 'WSF5_ATTRIBUTES': dtype('O'),
 'WSFG': dtype('float64'),
 'WSFG_ATTRIBUTES': dtype('O'),
 'WSFM': dtype('O'),
 'WSFM_ATTRIBUTES': dtype('O'),
 'HN02': dtype('O'),
 'HN02_ATTRIBUTES': dtype('O'),
 'HX02': dtype('O'),
 'HX02_ATTRIBUTES': dtype('O'),
 'LN02': dtype('O'),
 'LN02_ATTRIBUTES': dtype('O'),
 'LX02': dtype('O'),
 'LX02_ATTRIBUTES': dtype('O'),
 'MN02': dtype('O'),
 'MN02_ATTRIBUTES': dtype('O'),
 'MX02': dtype('O'),
 'MX02_ATTRIBUTES': dtype('O'),
 'HN03': dtype('O'),
 'HN03_ATTRIBUTES': dtype('O'),
 'HX03': dtype('O'),
 'HX03_ATTRIBUTES': dtype('O'),
 'LN03': dtype('O'),
 'LN03_ATTRIBUTES': dtype('O'),
 'LX03': dtype('O'),
 'LX03_ATTRIBUTES': dtype('O'),
 'MN03': dtype('O'),
 'MN03_ATTRIBUTES': dtype('O'),
 'MX03': dtype('O'),
 'MX03_ATTRIBUTES': dtype('O'),
 '<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">': dtype('O'),
 'HN04': dtype('O'),
 'HN04_ATTRIBUTES': dtype('O'),
 'HN05': dtype('O'),
 'HN05_ATTRIBUTES': dtype('O'),
 'HN06': dtype('O'),
 'HN06_ATTRIBUTES': dtype('O'),
 'HN07': dtype('O'),
 'HN07_ATTRIBUTES': dtype('O'),
 'HN08': dtype('O'),
 'HN08_ATTRIBUTES': dtype('O'),
 'HN09': dtype('O'),
 'HN09_ATTRIBUTES': dtype('O'),
 'HX04': dtype('O'),
 'HX04_ATTRIBUTES': dtype('O'),
 'HX05': dtype('O'),
 'HX05_ATTRIBUTES': dtype('O'),
 'HX06': dtype('O'),
 'HX06_ATTRIBUTES': dtype('O'),
 'HX07': dtype('O'),
 'HX07_ATTRIBUTES': dtype('O'),
 'HX08': dtype('O'),
 'HX08_ATTRIBUTES': dtype('O'),
 'HX09': dtype('O'),
 'HX09_ATTRIBUTES': dtype('O'),
 'LN04': dtype('O'),
 'LN04_ATTRIBUTES': dtype('O'),
 'LN05': dtype('O'),
 'LN05_ATTRIBUTES': dtype('O'),
 'LN06': dtype('O'),
 'LN06_ATTRIBUTES': dtype('O'),
 'LN07': dtype('O'),
 'LN07_ATTRIBUTES': dtype('O'),
 'LN08': dtype('O'),
 'LN08_ATTRIBUTES': dtype('O'),
 'LN09': dtype('O'),
 'LN09_ATTRIBUTES': dtype('O'),
 'LX04': dtype('O'),
 'LX04_ATTRIBUTES': dtype('O'),
 'LX05': dtype('O'),
 'LX05_ATTRIBUTES': dtype('O'),
 'LX06': dtype('O'),
 'LX06_ATTRIBUTES': dtype('O'),
 'LX07': dtype('O'),
 'LX07_ATTRIBUTES': dtype('O'),
 'LX08': dtype('O'),
 'LX08_ATTRIBUTES': dtype('O'),
 'LX09': dtype('O'),
 'LX09_ATTRIBUTES': dtype('O'),
 'MN04': dtype('O'),
 'MN04_ATTRIBUTES': dtype('O'),
 'MN05': dtype('O'),
 'MN05_ATTRIBUTES': dtype('O'),
 'MN06': dtype('O'),
 'MN06_ATTRIBUTES': dtype('O'),
 'MN07': dtype('O'),
 'MN07_ATTRIBUTES': dtype('O'),
 'MN08': dtype('O'),
 'MN08_ATTRIBUTES': dtype('O'),
 'MN09': dtype('O'),
 'MN09_ATTRIBUTES': dtype('O'),
 'MX04': dtype('O'),
 'MX04_ATTRIBUTES': dtype('O'),
 'MX05': dtype('O'),
 'MX05_ATTRIBUTES': dtype('O'),
 'MX06': dtype('O'),
 'MX06_ATTRIBUTES': dtype('O'),
 'MX07': dtype('O'),
 'MX07_ATTRIBUTES': dtype('O'),
 'MX08': dtype('O'),
 'MX08_ATTRIBUTES': dtype('O'),
 'MX09': dtype('O'),
 'MX09_ATTRIBUTES': dtype('O')}

Join Station ID to Zip Code CSV, and only filter the columns that are actually needed.

In [11]:
%%sql

us_data_all_df <<

SELECT z.station_id,
       z.zip_code,
       a.*
FROM read_csv('artifacts/us_data_all_zip.csv') z
    LEFT JOIN read_csv('artifacts/us_data.csv') a
        ON z.station_id = a.STATION
LIMIT 10

In [12]:
us_data_all_df

,station_id,zip_code,STATION,DATE,LATITUDE,LONGITUDE,ELEVATION,NAME,DP01,DP01_ATTRIBUTES,...,MX05,MX05_ATTRIBUTES,MX06,MX06_ATTRIBUTES,MX07,MX07_ATTRIBUTES,MX08,MX08_ATTRIBUTES,MX09,MX09_ATTRIBUTES
0,US1MDFR0038,21701,US1MDFR0038,2019-08-01,39.419264,-77.430926,100.0,"FREDERICK 1.0 SW, MD US",9.0,",N",...,None,None,None,None,None,None,None,None,None,None
1,US1MDFR0038,21701,US1MDFR0038,2019-09-01,39.419264,-77.430926,100.0,"FREDERICK 1.0 SW, MD US",5.0,",N",...,None,None,None,None,None,None,None,None,None,None
2,US1MDFR0038,21701,US1MDFR0038,2019-10-01,39.419264,-77.430926,100.0,"FREDERICK 1.0 SW, MD US",12.0,",N",...,None,None,None,None,None,None,None,None,None,None
3,US1MDFR0038,21701,US1MDFR0038,2019-12-01,39.419264,-77.430926,100.0,"FREDERICK 1.0 SW, MD US",14.0,"1,N",...,None,None,None,None,None,None,None,None,None,None
4,US1MDFR0038,21701,US1MDFR0038,2020-01-01,39.419264,-77.430926,100.0,"FREDERICK 1.0 SW, MD US",11.0,",N",...,None,None,None,None,None,None,None,None,None,None
5,US1MDFR0038,21701,US1MDFR0038,2020-02-01,39.419264,-77.430926,100.0,"FREDERICK 1.0 SW, MD US",15.0,",N",...,None,None,None,None,None,None,None,None,None,None
6,US1MDFR0038,21701,US1MDFR0038,2020-03-01,39.419264,-77.430926,100.0,"FREDERICK 1.0 SW, MD US",20.0,",N",...,None,None,None,None,None,None,None,None,None,None
7,US1MDFR0038,21701,US1MDFR0038,2020-04-01,39.419264,-77.430926,100.0,"FREDERICK 1.0 SW, MD US",19.0,",N",...,None,None,None,None,None,None,None,None,None,None
8,US1MDFR0038,21701,US1MDFR0038,2020-05-01,39.419264,-77.430926,100.0,"FREDERICK 1.0 SW, MD US",14.0,",N",...,None,None,None,None,None,None,None,None,None,None
9,US1MDFR0038,21701,US1MDFR0038,2020-06-01,39.419264,-77.430926,100.0,"FREDERICK 1.0 SW, MD US",10.0,"1,N",...,None,None,None,None,None,None,None,None,None,None